config/routes.rb
Rails.application.routes.draw do
  resources :pic_gals
  root 'application#index'
  # root 'pic_gals#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/pic_gal.rb
class PicGal < ApplicationRecord
    has_attached_file :img, :styles => { medium: "300x300>", :small => "150x150>", thumb: "100x100>" },
    :url  => "/upload_images/:id/:style/:basename.:extension",
    :path => ":rails_root/public/upload_images/:id/:style/:basename.:extension"

    validates_attachment_presence :img
    validates_attachment_size :img, :less_than => 5.megabytes
    validates_attachment_content_type :img, :content_type => ['image/jpeg', 'image/png']
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def index
    @pic_gals = PicGal.all
    render file: "/app/views/home"
  end
end

app/controllers/pic_gals_controller.rb
class PicGalsController < ApplicationController
  before_action :set_pic_gal, only: [:show, :edit, :update, :destroy]

  # GET /pic_gals
  # GET /pic_gals.json
  def index
    @pic_gals = PicGal.all
  end

  # GET /pic_gals/1
  # GET /pic_gals/1.json
  def show
  end

  # GET /pic_gals/new
  def new
    @pic_gal = PicGal.new
  end

  # GET /pic_gals/1/edit
  def edit
  end

  # POST /pic_gals
  # POST /pic_gals.json
  def create
    @pic_gal = PicGal.new(pic_gal_params)

    respond_to do |format|
      if @pic_gal.save
        format.html { redirect_to @pic_gal, notice: 'Pic gal was successfully created.' }
        format.json { render :show, status: :created, location: @pic_gal }
      else
        format.html { render :new }
        format.json { render json: @pic_gal.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pic_gals/1
  # PATCH/PUT /pic_gals/1.json
  def update
    respond_to do |format|
      if @pic_gal.update(pic_gal_params)
        format.html { redirect_to @pic_gal, notice: 'Pic gal was successfully updated.' }
        format.json { render :show, status: :ok, location: @pic_gal }
      else
        format.html { render :edit }
        format.json { render json: @pic_gal.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pic_gals/1
  # DELETE /pic_gals/1.json
  def destroy
    @pic_gal.destroy
    respond_to do |format|
      format.html { redirect_to pic_gals_url, notice: 'Pic gal was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pic_gal
      @pic_gal = PicGal.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pic_gal_params
      params.require(:pic_gal).permit(:title, :img, :notes)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def active_class(link_path)
        current_page?(link_path) ? "active" : ""
    end
end

app/helpers/pic_gals_helper.rb
module PicGalsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Gallery</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all',
                                              'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
      </script>
    <![endif]-->
  </head>
  <body>
    <header class="navbar navbar-fixed-top navbar-inverse">
      <div class="container">
        <%= link_to "Gallery", '#', id: "logo",:class=>"navbar-brand" %>
        <nav>
          <ul class="nav navbar-nav navbar-right">
            <li class="<%= active_class('/') %>"><%= link_to "Home", "/"  %></li>
            <li class="<%= active_class(pic_gals_path) %>"><%= link_to "Gallery CRUD", pic_gals_path %></li>
          </ul>
        </nav>
      </div>
    </header>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/pic_gals/_form.html.erb
<%= form_with(model: pic_gal, local: true, html: { multipart: true })  do |form| %>
  <% if pic_gal.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(pic_gal.errors.count, "error") %> prohibited this pic_gal from being saved:</h2>

      <ul>
      <% pic_gal.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :pic_gal_title, class: 'form-control' %>
  </div>

  <div class="field">
    <%= form.label :img %>
    <%= form.file_field :img, id: :pic_gal_img, class: 'form-control' %>
  </div>

  <div class="field">
    <%= form.label :notes %>
    <%= form.text_area :notes, id: :pic_gal_notes, class: 'form-control' %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/pic_gals/edit.html.erb
<h1>Editing Pic Gal</h1>

<%= render 'form', pic_gal: @pic_gal %>

<%= link_to 'Show', @pic_gal %> |
<%= link_to 'Back', pic_gals_path %>

app/views/pic_gals/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Pict</h1>

<table class="table">
  <thead>
    <tr>
      <th>Title</th>
      <th>Img</th>
      <th>Notes</th>
      <th colspan="3"><center>Action</center></th>
    </tr>
  </thead>

  <tbody>
    <% @pic_gals.each do |pic_gal| %>
      <tr>
        <td><%= pic_gal.title %></td>
        <td><%= image_tag pic_gal.img.url(:thumb) %></td>
        <td><%= pic_gal.notes %></td>
        <td><center><%= link_to 'Show', pic_gal, class: 'btn btn-primary' %></center></td>
        <td><center><%= link_to 'Edit', edit_pic_gal_path(pic_gal), class: 'btn btn-warning' %></center></td>
        <td><center><%= link_to 'Destroy', pic_gal, class: 'btn btn-danger', method: :delete, data: { confirm: 'Are you sure?' } %></center></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Pict', new_pic_gal_path %>

app/views/pic_gals/new.html.erb
<h1>New Pict</h1>

<%= render 'form', pic_gal: @pic_gal %>

<%= link_to 'Back', pic_gals_path %>

app/views/pic_gals/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @pic_gal.title %>
</p>

<p>
  <strong>Img:</strong><br>
  <%= image_tag @pic_gal.img.url(:medium) %>
</p>

<p>
  <strong>Notes:</strong>
  <%= @pic_gal.notes %>
</p>

<%= link_to 'Edit', edit_pic_gal_path(@pic_gal) %> |
<%= link_to 'Back', pic_gals_path %>